"""add_hls_url_to_instances

Revision ID: 0f28ec5aefd7
Revises: 1b1d86351f87
Create Date: 2026-02-14 22:07:06.117082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f28ec5aefd7'
down_revision: Union[str, Sequence[str], None] = '1b1d86351f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('osr_instances', sa.Column('hls_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('osr_instances', 'hls_url')
    # ### end Alembic commands ###
